using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Reflection;
using System.Security.Cryptography;
using GamePlay;
using UnityEditor;
using UnityEditor.U2D;
using UnityEngine;
using UnityEngine.U2D;
using YooAsset;
using YooAsset.Editor;
using Process = System.Diagnostics.Process;
using ProcessStartInfo = System.Diagnostics.ProcessStartInfo;

public class CheckBundleWindow : EditorWindow
{
    private const string AutoDescPrefix = "[AutoGenerated:Tool/CheckBundle]";
    private const string DefaultRootFolder = "Assets/InRemote";

    // ===== 固定构建参数（你要改就改这里） =====
    private const string FixedPackageName = "Tile";
    private const string FixedRootFolder = "Assets/InRemote";
    private const string FixedBuildOutputRoot = @"E:/RH04/R04/Bundles";

    private const BuildTarget FixedBuildTarget = BuildTarget.Android;
    private const bool FixedClearBuildCache = false;              // false = 增量
    private const bool FixedUseAssetDependDB = true;
    private const bool FixedVerifyBuildingResult = true;
    private const bool FixedEnableSharePackRule = true;

    private const ECompressOption FixedCompressOption = ECompressOption.LZ4;
    private const EFileNameStyle FixedFileNameStyle = EFileNameStyle.BundleName;
    private const EBuildinFileCopyOption FixedCopyBuildinFileOption = EBuildinFileCopyOption.ClearAndCopyByTags;
    private const string FixedCopyBuildinFileParams = "BuildIn";

    private const string FixedEncryptionClassName = "SecureAesCtrEncryption";

    // 这两个如果和你项目里的下拉不一致，就改成你项目里的完整类名
    private const string FixedManifestProcessClassName = "YooAsset.Editor.ManifestProcessNone";
    private const string FixedManifestRestoreClassName = "YooAsset.Editor.ManifestRestoreNone";

    private string _packageName = FixedPackageName;
    private string _rootFolder = FixedRootFolder;
    private string _buildVersion = GlobalSetting.ResourceVersion;

    private bool _clearManagedCollectors = true;
    private bool _removeStaleManagedGroups = false;

    private Vector2 _scroll;

    [MenuItem("Tool/CheckBundle")]
    public static void Open()
    {
        GetWindow<CheckBundleWindow>("CheckBundle");
    }

    private void OnEnable()
    {
        _packageName = FixedPackageName;
        _rootFolder = FixedRootFolder;
        if (string.IsNullOrWhiteSpace(_buildVersion))
            _buildVersion = "v1";
    }

    private void OnGUI()
    {
        EditorGUILayout.Space();

        EditorGUILayout.LabelField("YooAsset InRemote Group Sync + Build", EditorStyles.boldLabel);
        EditorGUILayout.HelpBox(
            "扫描 Assets/InRemote 下直接包含资源文件的文件夹，并同步到 YooAsset Group。\n" +
            "例如：Assets/InRemote/Coin1of3/1 -> GroupName = Coin1of3_1, AssetTags = Coin1of3_1\n" +
            "顶层 BuildIn 文件夹会跳过。\n\n" +
            "Build 参数已写死，只有 BuildVersion 可输入。",
            MessageType.Info);

        EditorGUILayout.Space();
        _scroll = EditorGUILayout.BeginScrollView(_scroll);

        using (new EditorGUI.DisabledScope(true))
        {
            EditorGUILayout.TextField("Package Name", _packageName);
            EditorGUILayout.TextField("Root Folder", _rootFolder);
            EditorGUILayout.TextField("Build Output Root", FixedBuildOutputRoot);
            EditorGUILayout.EnumPopup("Build Target", FixedBuildTarget);
            EditorGUILayout.Toggle("Clear Build Cache", FixedClearBuildCache);
            EditorGUILayout.Toggle("Use Asset Depend DB", FixedUseAssetDependDB);
            EditorGUILayout.EnumPopup("Compression", FixedCompressOption);
            EditorGUILayout.EnumPopup("File Name Style", FixedFileNameStyle);
            EditorGUILayout.EnumPopup("Copy Buildin File Option", FixedCopyBuildinFileOption);
            EditorGUILayout.TextField("Copy Buildin File Param", FixedCopyBuildinFileParams);
            EditorGUILayout.TextField("Encryption Services", FixedEncryptionClassName);
            EditorGUILayout.TextField("Manifest Process Services", FixedManifestProcessClassName);
            EditorGUILayout.TextField("Manifest Restore Services", FixedManifestRestoreClassName);
        }

        EditorGUILayout.Space();
        _buildVersion = EditorGUILayout.TextField("Build Version", _buildVersion);

        EditorGUILayout.Space();
        _clearManagedCollectors = EditorGUILayout.ToggleLeft("Clear managed group's collectors before rebuild", _clearManagedCollectors);
        _removeStaleManagedGroups = EditorGUILayout.ToggleLeft("Remove stale auto-generated groups", _removeStaleManagedGroups);

        EditorGUILayout.Space();
        using (new EditorGUILayout.HorizontalScope())
        {
            if (GUILayout.Button("Preview", GUILayout.Height(30)))
            {
                PreviewFolders();
            }

            if (GUILayout.Button("Sync To YooAsset", GUILayout.Height(30)))
            {
                SyncToYooAsset();
            }

            if (GUILayout.Button("处理图集", GUILayout.Height(30)))
            {
                ProcessAtlases();
            }
        }

        EditorGUILayout.Space();
        using (new EditorGUILayout.HorizontalScope())
        {
            if (GUILayout.Button("Sync + Build YooAsset + Open Log", GUILayout.Height(34)))
            {
                SyncAndBuild();
            }

            if (GUILayout.Button("Build YooAsset + Open Log", GUILayout.Height(34)))
            {
                BuildYooAssetAndOpenLog();
            }
        }

        EditorGUILayout.Space();
        EditorGUILayout.HelpBox(
            "默认 Collector 配置：\n" +
            "- ActiveRule = EnableGroup\n" +
            "- CollectorType = MainAssetCollector\n" +
            "- AddressRule = AddressByFileName\n" +
            "- PackRule = PackGroup\n" +
            "- FilterRule = CollectAll\n\n" +
            "默认 Build 配置：\n" +
            "- BuildPipeline = ScriptableBuildPipeline\n" +
            "- Clear Build Cache = false（增量）\n" +
            "- Use Asset Depend DB = true\n" +
            "- Compression = LZ4\n" +
            "- File Name Style = BundleName\n" +
            "- Copy Buildin File Option = ClearAndCopyByTags\n" +
            "- Copy Buildin File Param = BuildIn\n\n" +
            "处理图集：\n" +
            "- 把文件夹内图片改成 Sprite\n" +
            "- 不生成 mipmaps\n" +
            "- 创建或补全同名 SpriteAtlas\n" +
            "- 图集名默认按 bundleName 处理，例如：challenge_asset、Coin1of3_1_asset\n" +
            "- 关闭 Rotation / Tight Packing\n" +
            "- 对固定平台启用 Override，格式 ASTC 6x6\n" +
            "- 如果当前文件夹里已存在同名图集，则直接跳过，不再重复处理",
            MessageType.None);

        EditorGUILayout.EndScrollView();
    }

    private void SyncAndBuild()
    {
        if (!SyncToYooAssetInternal(showDialog: true))
            return;

        BuildYooAssetAndOpenLog();
    }

    private void PreviewFolders()
    {
        if (!ValidateRootFolder())
            return;

        List<GroupFolderInfo> folders = CollectGroupFolders(_rootFolder);
        if (folders.Count == 0)
        {
            Debug.LogWarning($"[CheckBundle] 没有在 {_rootFolder} 下找到可用文件夹。");
            return;
        }

        Debug.Log($"[CheckBundle] Preview count = {folders.Count}");
        foreach (var info in folders)
        {
            Debug.Log($"[CheckBundle] {info.AssetFolderPath}  =>  Group={info.GroupName}, Tag={info.AssetTag}");
        }
    }

    private void SyncToYooAsset()
    {
        SyncToYooAssetInternal(showDialog: true);
    }

    private bool SyncToYooAssetInternal(bool showDialog)
    {
        if (!ValidateRootFolder())
            return false;

        AssetBundleCollectorSetting setting = ResolveCollectorSetting();
        if (setting == null)
        {
            if (showDialog)
                EditorUtility.DisplayDialog("CheckBundle", "没有找到 AssetBundleCollectorSetting 资源。请先创建 YooAsset 的 Collector Setting。", "OK");
            return false;
        }

        Undo.RecordObject(setting, "Tool/CheckBundle Sync");

        AssetBundleCollectorPackage package = GetOrCreatePackage(setting, _packageName);
        if (package.Groups == null)
            package.Groups = new List<AssetBundleCollectorGroup>();

        List<GroupFolderInfo> folderInfos = CollectGroupFolders(_rootFolder);
        HashSet<string> currentAutoGroupNames = new HashSet<string>(folderInfos.Select(x => x.GroupName), StringComparer.OrdinalIgnoreCase);

        int created = 0;
        int updated = 0;
        int removed = 0;

        foreach (var info in folderInfos)
        {
            bool isNew;
            AssetBundleCollectorGroup group = GetOrCreateGroup(package, info.GroupName, out isNew);
            ConfigureGroup(group, info, _clearManagedCollectors);

            if (isNew)
                created++;
            else
                updated++;
        }

        if (_removeStaleManagedGroups)
        {
            for (int i = package.Groups.Count - 1; i >= 0; i--)
            {
                AssetBundleCollectorGroup group = package.Groups[i];
                if (group == null)
                    continue;

                if (!currentAutoGroupNames.Contains(group.GroupName))
                {
                    package.Groups.RemoveAt(i);
                    removed++;
                }
            }
        }

        package.FixConfigError();
        setting.FixAllPackageConfigError();

        EditorUtility.SetDirty(setting);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log(
            $"[CheckBundle] Sync finished. " +
            $"Package={_packageName}, Root={_rootFolder}, " +
            $"Created={created}, Updated={updated}, Removed={removed}, TotalFolders={folderInfos.Count}");

        if (showDialog)
        {
            EditorUtility.DisplayDialog(
                "CheckBundle",
                $"同步完成。\n\nCreated: {created}\nUpdated: {updated}\nRemoved: {removed}\nFolders: {folderInfos.Count}",
                "OK");
        }

        return true;
    }

    private void ProcessAtlases()
    {
        if (!ValidateRootFolder())
            return;

        List<GroupFolderInfo> folderInfos = CollectGroupFolders(_rootFolder);
        if (folderInfos.Count == 0)
        {
            EditorUtility.DisplayDialog("CheckBundle", "没有找到可处理的文件夹。", "OK");
            return;
        }

        string platformName = GetAtlasPlatformName(FixedBuildTarget);

        int processedFolderCount = 0;
        int skippedFolderCount = 0;
        int changedTextureCount = 0;
        int createdAtlasCount = 0;
        int updatedAtlasCount = 0;
        int failedCount = 0;

        try
        {
            for (int i = 0; i < folderInfos.Count; i++)
            {
                GroupFolderInfo info = folderInfos[i];
                string atlasName = GetAtlasName(info.GroupName);

                EditorUtility.DisplayProgressBar(
                    "处理图集",
                    $"{atlasName} ({i + 1}/{folderInfos.Count})",
                    (i + 1f) / folderInfos.Count);

                if (!AssetDatabase.IsValidFolder(info.AssetFolderPath))
                {
                    skippedFolderCount++;
                    continue;
                }

                // 如果当前文件夹里已经有同名图集，就直接跳过，避免重复处理导致 hash 变化
                if (HasAtlasInFolder(info.AssetFolderPath, atlasName))
                {
                    skippedFolderCount++;
                    Debug.Log($"[CheckBundle] Skip atlas process, already exists: {info.AssetFolderPath}/{atlasName}.spriteatlas");
                    continue;
                }

                List<string> texturePaths = GetTexturePathsInFolder(info.AssetFolderPath);
                if (texturePaths.Count == 0)
                {
                    skippedFolderCount++;
                    continue;
                }

                processedFolderCount++;

                changedTextureCount += PrepareTexturesForAtlas(texturePaths);

                bool atlasCreated;
                SpriteAtlas atlas = FindOrCreateAtlas(atlasName, info.AssetFolderPath, out atlasCreated);
                if (atlas == null)
                {
                    failedCount++;
                    Debug.LogError($"[CheckBundle] 图集创建失败：{atlasName}  Folder={info.AssetFolderPath}");
                    continue;
                }

                if (atlasCreated)
                    createdAtlasCount++;
                else
                    updatedAtlasCount++;

                EnsureFolderPackedInAtlas(atlas, info.AssetFolderPath);
                ApplyAtlasSettings(atlas, platformName);
                EditorUtility.SetDirty(atlas);

                Debug.Log($"[CheckBundle] 处理图集完成：{atlasName}  Folder={info.AssetFolderPath}");
            }
        }
        finally
        {
            EditorUtility.ClearProgressBar();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        string message =
            $"处理完成。\n\n" +
            $"Processed Folders: {processedFolderCount}\n" +
            $"Skipped Folders: {skippedFolderCount}\n" +
            $"Changed Textures: {changedTextureCount}\n" +
            $"Created Atlases: {createdAtlasCount}\n" +
            $"Updated Atlases: {updatedAtlasCount}\n" +
            $"Failed: {failedCount}";

        Debug.Log($"[CheckBundle] Atlas Process Finished.\n{message}");
        EditorUtility.DisplayDialog("CheckBundle", message, "OK");
    }

    private bool ValidateRootFolder()
    {
        if (string.IsNullOrWhiteSpace(_rootFolder))
        {
            EditorUtility.DisplayDialog("CheckBundle", "Root Folder 不能为空。", "OK");
            return false;
        }

        if (!AssetDatabase.IsValidFolder(_rootFolder))
        {
            EditorUtility.DisplayDialog("CheckBundle", $"目录不存在：{_rootFolder}", "OK");
            return false;
        }

        return true;
    }

    private static AssetBundleCollectorSetting ResolveCollectorSetting()
    {
        string[] guids = AssetDatabase.FindAssets("t:AssetBundleCollectorSetting");
        if (guids == null || guids.Length == 0)
            return null;

        if (guids.Length > 1)
            Debug.LogWarning("[CheckBundle] Found multiple AssetBundleCollectorSetting assets. 将使用第一个。");

        string path = AssetDatabase.GUIDToAssetPath(guids[0]);
        return AssetDatabase.LoadAssetAtPath<AssetBundleCollectorSetting>(path);
    }

    private static AssetBundleCollectorPackage GetOrCreatePackage(AssetBundleCollectorSetting setting, string packageName)
    {
        if (setting.Packages == null)
            setting.Packages = new List<AssetBundleCollectorPackage>();

        AssetBundleCollectorPackage package = setting.Packages.FirstOrDefault(x => x != null && x.PackageName == packageName);
        if (package != null)
            return package;

        package = new AssetBundleCollectorPackage
        {
            PackageName = packageName,
            PackageDesc = "Auto created by Tool/CheckBundle",
            EnableAddressable = true,
            SupportExtensionless = false,
            LocationToLower = false,
            IncludeAssetGUID = false,
            AutoCollectShaders = false,
            IgnoreRuleName = nameof(NormalIgnoreRule),
            Groups = new List<AssetBundleCollectorGroup>()
        };

        setting.Packages.Add(package);
        return package;
    }

    private static AssetBundleCollectorGroup GetOrCreateGroup(
        AssetBundleCollectorPackage package,
        string groupName,
        out bool isNew)
    {
        AssetBundleCollectorGroup found = null;

        if (package.Groups != null)
            found = package.Groups.FirstOrDefault(x => x != null && x.GroupName == groupName);

        if (found != null)
        {
            isNew = false;
            return found;
        }

        var group = new AssetBundleCollectorGroup
        {
            GroupName = groupName,
            // GroupDesc = AutoDescPrefix,
            AssetTags = groupName,
            ActiveRuleName = nameof(EnableGroup),
            Collectors = new List<AssetBundleCollector>()
        };

        package.Groups.Add(group);
        isNew = true;
        return group;
    }

    private static void ConfigureGroup(
        AssetBundleCollectorGroup group,
        GroupFolderInfo info,
        bool clearManagedCollectors)
    {
        group.GroupName = info.GroupName;
        // group.GroupDesc = $"{AutoDescPrefix}|{info.AssetFolderPath}";
        group.AssetTags = info.AssetTag;
        group.ActiveRuleName = nameof(EnableGroup);

        if (group.Collectors == null)
            group.Collectors = new List<AssetBundleCollector>();

        AssetBundleCollector collector = null;

        if (!clearManagedCollectors)
            collector = group.Collectors.FirstOrDefault(x => x != null && x.CollectPath == info.AssetFolderPath);
        else
            group.Collectors.Clear();

        if (collector == null)
        {
            collector = new AssetBundleCollector();
            group.Collectors.Add(collector);
        }

        ConfigureCollector(collector, info);
    }

    private static void ConfigureCollector(AssetBundleCollector collector, GroupFolderInfo info)
    {
        collector.CollectPath = info.AssetFolderPath;
        collector.CollectorGUID = AssetDatabase.AssetPathToGUID(info.AssetFolderPath);
        collector.CollectorType = ECollectorType.MainAssetCollector;
        collector.AddressRuleName = nameof(AddressByFileName);
        collector.PackRuleName = nameof(PackGroup);
        collector.FilterRuleName = nameof(CollectAll);
        collector.AssetTags = info.AssetTag;
        collector.UserData = string.Empty;
    }

    // private static bool IsManagedGroup(AssetBundleCollectorGroup group)
    // {
    //     return group != null &&
    //            !string.IsNullOrEmpty(group.GroupDesc) &&
    //            group.GroupDesc.StartsWith(AutoDescPrefix, StringComparison.Ordinal);
    // }

    private static List<GroupFolderInfo> CollectGroupFolders(string rootFolder)
    {
        List<GroupFolderInfo> results = new List<GroupFolderInfo>();
        string rootFullPath = ToFullPath(rootFolder);
        if (!Directory.Exists(rootFullPath))
            return results;

        string[] allDirs = Directory.GetDirectories(rootFullPath, "*", SearchOption.AllDirectories);
        foreach (string dir in allDirs)
        {
            string assetPath = ToAssetPath(dir);
            if (string.IsNullOrEmpty(assetPath))
                continue;

            if (!AssetDatabase.IsValidFolder(assetPath))
                continue;

            if (ShouldSkipFolder(rootFolder, assetPath))
                continue;

            if (!ContainsDirectAssetFiles(dir))
                continue;

            string groupName = BuildGroupName(rootFolder, assetPath);
            if (string.IsNullOrEmpty(groupName))
                continue;

            results.Add(new GroupFolderInfo
            {
                AssetFolderPath = assetPath,
                GroupName = groupName,
                AssetTag = groupName
            });
        }

        results.Sort((a, b) => string.CompareOrdinal(a.AssetFolderPath, b.AssetFolderPath));
        return results;
    }

    private static bool ShouldSkipFolder(string rootFolder, string assetPath)
    {
        string relative = MakeRelativeAssetPath(rootFolder, assetPath);
        if (string.IsNullOrEmpty(relative))
            return true;

        string[] parts = relative.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
            return true;

        if (string.Equals(parts[0], "BuildIn", StringComparison.OrdinalIgnoreCase))
            return true;

        return false;
    }

    private static bool ContainsDirectAssetFiles(string fullDir)
    {
        string[] files = Directory.GetFiles(fullDir, "*", SearchOption.TopDirectoryOnly);
        foreach (string file in files)
        {
            string ext = Path.GetExtension(file);
            if (string.Equals(ext, ".meta", StringComparison.OrdinalIgnoreCase))
                continue;

            string fileName = Path.GetFileName(file);
            if (string.Equals(fileName, ".DS_Store", StringComparison.OrdinalIgnoreCase))
                continue;

            return true;
        }

        return false;
    }

    private static string BuildGroupName(string rootFolder, string folderAssetPath)
    {
        string relative = MakeRelativeAssetPath(rootFolder, folderAssetPath);
        if (string.IsNullOrEmpty(relative))
            return string.Empty;

        string[] parts = relative.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
            return string.Empty;

        for (int i = 0; i < parts.Length; i++)
            parts[i] = SanitizeName(parts[i]);

        return string.Join("_", parts);
    }

    private static string SanitizeName(string value)
    {
        if (string.IsNullOrEmpty(value))
            return string.Empty;

        value = value.Replace(" ", "_");
        value = value.Replace(";", "_");
        return value.Trim();
    }

    private static string MakeRelativeAssetPath(string rootFolder, string targetFolder)
    {
        string root = rootFolder.Replace("\\", "/").TrimEnd('/');
        string target = targetFolder.Replace("\\", "/").TrimEnd('/');

        if (!target.StartsWith(root + "/", StringComparison.OrdinalIgnoreCase))
            return string.Empty;

        return target.Substring(root.Length + 1);
    }

    private static string ToFullPath(string assetPath)
    {
        string projectRoot = Directory.GetParent(Application.dataPath).FullName.Replace("\\", "/");
        string path = assetPath.Replace("\\", "/");
        return Path.GetFullPath(Path.Combine(projectRoot, path)).Replace("\\", "/");
    }

    private static string ToAssetPath(string fullPath)
    {
        string normalized = fullPath.Replace("\\", "/");
        string projectRoot = Directory.GetParent(Application.dataPath).FullName.Replace("\\", "/");

        if (!normalized.StartsWith(projectRoot, StringComparison.OrdinalIgnoreCase))
            return null;

        string relative = normalized.Substring(projectRoot.Length).TrimStart('/');
        return relative;
    }

    // =========================
    // Atlas
    // =========================

    private static string GetAtlasName(string groupName)
    {
        if (string.IsNullOrWhiteSpace(groupName))
            return string.Empty;

        if (groupName.EndsWith("_asset", StringComparison.OrdinalIgnoreCase))
            return groupName;

        return groupName + "_asset";
    }

    private static bool HasAtlasInFolder(string folderAssetPath, string atlasName)
    {
        if (string.IsNullOrEmpty(folderAssetPath) || string.IsNullOrEmpty(atlasName))
            return false;

        string atlasPath = $"{folderAssetPath}/{atlasName}.spriteatlas";
        SpriteAtlas atlas = AssetDatabase.LoadAssetAtPath<SpriteAtlas>(atlasPath);
        return atlas != null;
    }

    private static List<string> GetTexturePathsInFolder(string folderAssetPath)
    {
        List<string> result = new List<string>();

        string[] guids = AssetDatabase.FindAssets("t:Texture2D", new[] { folderAssetPath });
        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            if (string.IsNullOrEmpty(path))
                continue;

            if (!IsTextureFile(path))
                continue;

            result.Add(path);
        }

        result.Sort(StringComparer.OrdinalIgnoreCase);
        return result;
    }

    private static bool IsTextureFile(string assetPath)
    {
        string ext = Path.GetExtension(assetPath).ToLowerInvariant();
        switch (ext)
        {
            case ".png":
            case ".jpg":
            case ".jpeg":
            case ".tga":
            case ".psd":
            case ".tif":
            case ".tiff":
            case ".bmp":
            case ".gif":
                return true;
            default:
                return false;
        }
    }

    private static int PrepareTexturesForAtlas(List<string> texturePaths)
    {
        int changedCount = 0;

        foreach (string texturePath in texturePaths)
        {
            TextureImporter importer = AssetImporter.GetAtPath(texturePath) as TextureImporter;
            if (importer == null)
                continue;

            bool changed = false;

            if (importer.textureType != TextureImporterType.Sprite)
            {
                importer.textureType = TextureImporterType.Sprite;
                changed = true;
            }

            if (importer.mipmapEnabled)
            {
                importer.mipmapEnabled = false;
                changed = true;
            }

            if (changed)
            {
                importer.SaveAndReimport();
                changedCount++;
            }
        }

        return changedCount;
    }

    private static SpriteAtlas FindOrCreateAtlas(string atlasName, string folderAssetPath, out bool created)
    {
        created = false;

        string atlasPathInFolder = $"{folderAssetPath}/{atlasName}.spriteatlas";
        SpriteAtlas atlas = AssetDatabase.LoadAssetAtPath<SpriteAtlas>(atlasPathInFolder);
        if (atlas != null)
            return atlas;

        string[] guids = AssetDatabase.FindAssets($"{atlasName} t:SpriteAtlas");
        List<string> matchedPaths = new List<string>();

        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            if (string.Equals(Path.GetFileNameWithoutExtension(path), atlasName, StringComparison.OrdinalIgnoreCase))
                matchedPaths.Add(path);
        }

        if (matchedPaths.Count > 0)
        {
            string preferred = matchedPaths.FirstOrDefault(x =>
                string.Equals(
                    NormalizePath(Path.GetDirectoryName(x)),
                    NormalizePath(folderAssetPath),
                    StringComparison.OrdinalIgnoreCase));

            string chosenPath = preferred ?? matchedPaths[0];
            atlas = AssetDatabase.LoadAssetAtPath<SpriteAtlas>(chosenPath);

            if (matchedPaths.Count > 1)
            {
                Debug.LogWarning(
                    $"[CheckBundle] 找到多个同名图集 {atlasName}，本次使用：{chosenPath}\n" +
                    string.Join("\n", matchedPaths));
            }

            return atlas;
        }

        atlas = new SpriteAtlas();
        AssetDatabase.CreateAsset(atlas, atlasPathInFolder);
        created = true;

        Debug.Log($"[CheckBundle] 已创建图集：{atlasPathInFolder}");
        return atlas;
    }

    private static void EnsureFolderPackedInAtlas(SpriteAtlas atlas, string folderAssetPath)
    {
        DefaultAsset folderObj = AssetDatabase.LoadAssetAtPath<DefaultAsset>(folderAssetPath);
        if (folderObj == null)
        {
            Debug.LogError($"[CheckBundle] 无法加载文件夹对象：{folderAssetPath}");
            return;
        }

        UnityEngine.Object[] packables = atlas.GetPackables();
        bool alreadyHasFolder = packables.Any(x =>
            string.Equals(
                NormalizePath(AssetDatabase.GetAssetPath(x)),
                NormalizePath(folderAssetPath),
                StringComparison.OrdinalIgnoreCase));

        if (alreadyHasFolder)
            return;

        List<UnityEngine.Object> removable = new List<UnityEngine.Object>();
        foreach (UnityEngine.Object obj in packables)
        {
            if (obj == null)
                continue;

            string packablePath = NormalizePath(AssetDatabase.GetAssetPath(obj));
            if (string.IsNullOrEmpty(packablePath))
                continue;

            if (string.Equals(packablePath, NormalizePath(folderAssetPath), StringComparison.OrdinalIgnoreCase))
                continue;

            if (IsPathInFolder(packablePath, folderAssetPath))
                removable.Add(obj);
        }

        if (removable.Count > 0)
            atlas.Remove(removable.ToArray());

        atlas.Add(new UnityEngine.Object[] { folderObj });
    }

    private static void ApplyAtlasSettings(SpriteAtlas atlas, string platformName)
    {
        SpriteAtlasPackingSettings packingSettings = atlas.GetPackingSettings();
        packingSettings.enableRotation = false;
        packingSettings.enableTightPacking = false;
        atlas.SetPackingSettings(packingSettings);

        SpriteAtlasTextureSettings textureSettings = atlas.GetTextureSettings();
        textureSettings.generateMipMaps = false;
        atlas.SetTextureSettings(textureSettings);

        if (!string.IsNullOrEmpty(platformName))
        {
            TextureImporterPlatformSettings platformSettings = atlas.GetPlatformSettings(platformName);
            platformSettings.overridden = true;
            platformSettings.format = TextureImporterFormat.ASTC_6x6;
            platformSettings.crunchedCompression = false;
            platformSettings.compressionQuality = 100;
            atlas.SetPlatformSettings(platformSettings);
        }
    }

    private static string GetAtlasPlatformName(BuildTarget buildTarget)
    {
        switch (buildTarget)
        {
            case BuildTarget.Android:
                return "Android";

            case BuildTarget.iOS:
                return "iPhone";

            case BuildTarget.tvOS:
                return "tvOS";

            default:
                Debug.LogWarning($"[CheckBundle] 当前图集处理平台未专门映射：{buildTarget}，将跳过图集平台 Override。");
                return string.Empty;
        }
    }

    private static bool IsPathInFolder(string assetPath, string folderAssetPath)
    {
        string folder = NormalizePath(folderAssetPath).TrimEnd('/') + "/";
        string path = NormalizePath(assetPath);
        return path.StartsWith(folder, StringComparison.OrdinalIgnoreCase);
    }

    private static string NormalizePath(string path)
    {
        if (string.IsNullOrEmpty(path))
            return string.Empty;
        return path.Replace("\\", "/");
    }

    // =========================
    // Build
    // =========================

    private void BuildYooAssetAndOpenLog()
    {
        if (string.IsNullOrWhiteSpace(_packageName))
        {
            EditorUtility.DisplayDialog("CheckBundle", "Package Name 不能为空。", "OK");
            return;
        }

        if (string.IsNullOrWhiteSpace(_buildVersion))
        {
            EditorUtility.DisplayDialog("CheckBundle", "Build Version 不能为空。", "OK");
            return;
        }

        Directory.CreateDirectory(FixedBuildOutputRoot);

        string currentVersionDir = GetCurrentVersionOutputDirectory();
        string compareBuildDir = null;
        Dictionary<string, string> oldHashes;

        // 优先拿“当前版本目录”做对比，并在 build 前改名备份，避免 YooAsset 报目录已存在
        if (Directory.Exists(currentVersionDir))
        {
            oldHashes = SnapshotBundleFileHashes(currentVersionDir, _packageName);

            string backupDir = BackupExistingVersionDirectory(currentVersionDir);
            compareBuildDir = backupDir;

            Debug.Log($"[CheckBundle] Existing version dir moved:\n{currentVersionDir}\n=>\n{backupDir}");
        }
        else
        {
            compareBuildDir = FindLatestBuildVersionDirectory(FixedBuildOutputRoot, _packageName, FixedBuildTarget);
            oldHashes = string.IsNullOrEmpty(compareBuildDir)
                ? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
                : SnapshotBundleFileHashes(compareBuildDir, _packageName);
        }

        Debug.Log($"[CheckBundle] Start build. Package={_packageName}, Version={_buildVersion}, Target={FixedBuildTarget}");

        BuildResult buildResult = ExecuteBuild();

        string logPath;
        if (!buildResult.Success)
        {
            logPath = WriteBuildFailLog(compareBuildDir, buildResult);
            OpenWithDefaultApp(logPath);

            Debug.LogError($"[CheckBundle] Build failed : {buildResult.ErrorInfo}");
            EditorUtility.DisplayDialog("CheckBundle", $"Build 失败。\nLog: {logPath}", "OK");
            return;
        }

        string newBuildDir = buildResult.OutputPackageDirectory;
        Dictionary<string, string> newHashes = SnapshotBundleFileHashes(newBuildDir, _packageName);

        UpAssetCopyResult upAssetResult = RefreshUpAssetDirectory(newBuildDir, oldHashes, newHashes);

        logPath = WriteBuildSuccessLog(compareBuildDir, oldHashes, newBuildDir, newHashes, upAssetResult);
        OpenWithDefaultApp(logPath);

        Debug.Log(
            $"[CheckBundle] Build success : {newBuildDir}\n" +
            $"[CheckBundle] upAsset refreshed : {upAssetResult.OutputDir}\n" +
            $"[CheckBundle] copied changed bundles = {upAssetResult.BundleFiles.Count}, metadata files = {upAssetResult.MetadataFiles.Count}");

        EditorUtility.DisplayDialog(
            "CheckBundle",
            $"Build 完成。\n\nupAsset: {upAssetResult.OutputDir}\nChanged Bundles: {upAssetResult.BundleFiles.Count}\nMetadata Files: {upAssetResult.MetadataFiles.Count}\nLog: {logPath}",
            "OK");
    }

    private string GetCurrentVersionOutputDirectory()
    {
        return Path.Combine(
            FixedBuildOutputRoot,
            FixedBuildTarget.ToString(),
            _packageName,
            _buildVersion
        ).Replace("\\", "/");
    }

    private static string BackupExistingVersionDirectory(string versionDir)
    {
        if (string.IsNullOrEmpty(versionDir) || !Directory.Exists(versionDir))
            return versionDir;

        string parentDir = Path.GetDirectoryName(versionDir);
        string folderName = Path.GetFileName(versionDir);

        string time = DateTime.Now.ToString("yyyyMMdd_HHmmss");
        string backupDir = Path.Combine(parentDir, $"{folderName}_old_{time}");

        int index = 1;
        while (Directory.Exists(backupDir))
        {
            backupDir = Path.Combine(parentDir, $"{folderName}_old_{time}_{index}");
            index++;
        }

        Directory.Move(versionDir, backupDir);
        return backupDir.Replace("\\", "/");
    }

    private BuildResult ExecuteBuild()
    {
        ScriptableBuildParameters buildParameters = new ScriptableBuildParameters();
        FillCommonBuildParameters(buildParameters, EBuildPipeline.ScriptableBuildPipeline.ToString());

        // SBP 需要显式设置内置着色器 bundle 名
        buildParameters.BuiltinShadersBundleName = GetBuiltinShaderBundleName(_packageName);

        // 某些版本有这个字段，有些没有，用反射兜底
        SetMemberValue(buildParameters, "EnableSharePackRule", FixedEnableSharePackRule);

        ScriptableBuildPipeline pipeline = new ScriptableBuildPipeline();
        return pipeline.Run(buildParameters, true);
    }

    private void FillCommonBuildParameters(BuildParameters p, string pipelineName)
    {
        p.BuildOutputRoot = FixedBuildOutputRoot;
        p.BuildinFileRoot = AssetBundleBuilderHelper.GetStreamingAssetsRoot();
        p.BuildPipeline = pipelineName;
        p.BuildBundleType = (int)EBuildBundleType.AssetBundle;
        p.BuildTarget = FixedBuildTarget;
        p.PackageName = _packageName;
        p.PackageVersion = _buildVersion;

        SetMemberValue(p, "PackageNote", string.Empty);
        SetMemberValue(p, "VerifyBuildingResult", FixedVerifyBuildingResult);
        SetMemberValue(p, "CompressOption", FixedCompressOption);
        SetMemberValue(p, "FileNameStyle", FixedFileNameStyle);
        SetMemberValue(p, "BuildinFileCopyOption", FixedCopyBuildinFileOption);
        SetMemberValue(p, "BuildinFileCopyParams", FixedCopyBuildinFileParams);
        SetMemberValue(p, "ClearBuildCacheFiles", FixedClearBuildCache);
        SetMemberValue(p, "UseAssetDependencyDB", FixedUseAssetDependDB);

        object encryption = CreateInstanceByTypeName(FixedEncryptionClassName);
        object manifestProcess = CreateInstanceByTypeName(FixedManifestProcessClassName);
        object manifestRestore = CreateInstanceByTypeName(FixedManifestRestoreClassName);

        if (encryption != null) SetMemberValue(p, "EncryptionServices", encryption);
        if (manifestProcess != null) SetMemberValue(p, "ManifestProcessServices", manifestProcess);
        if (manifestRestore != null) SetMemberValue(p, "ManifestRestoreServices", manifestRestore);
    }

    private string GetBuiltinShaderBundleName(string packageName)
    {
        bool uniqueBundleName = false;
        AssetBundleCollectorSetting setting = ResolveCollectorSetting();
        if (setting != null)
            uniqueBundleName = setting.UniqueBundleName;

        var packRuleResult = DefaultPackRule.CreateShadersPackRuleResult();
        return packRuleResult.GetBundleName(packageName, uniqueBundleName);
    }

    private static void SetMemberValue(object obj, string memberName, object value)
    {
        if (obj == null || string.IsNullOrEmpty(memberName))
            return;

        Type type = obj.GetType();

        FieldInfo field = type.GetField(memberName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
        if (field != null)
        {
            field.SetValue(obj, value);
            return;
        }

        PropertyInfo property = type.GetProperty(memberName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
        if (property != null && property.CanWrite)
            property.SetValue(obj, value, null);
    }

    private static object CreateInstanceByTypeName(string typeName)
    {
        if (string.IsNullOrWhiteSpace(typeName))
            return null;

        Type type = FindType(typeName);
        if (type == null)
        {
            Debug.LogWarning($"[CheckBundle] Can not find type : {typeName}");
            return null;
        }

        try
        {
            return Activator.CreateInstance(type);
        }
        catch (Exception e)
        {
            Debug.LogWarning($"[CheckBundle] Create instance failed : {typeName}\n{e}");
            return null;
        }
    }

    private static Type FindType(string typeName)
    {
        Type type = Type.GetType(typeName);
        if (type != null)
            return type;

        Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
        foreach (Assembly asm in assemblies)
        {
            type = asm.GetType(typeName);
            if (type != null)
                return type;
        }

        foreach (Assembly asm in assemblies)
        {
            Type[] types;
            try
            {
                types = asm.GetTypes();
            }
            catch
            {
                continue;
            }

            for (int i = 0; i < types.Length; i++)
            {
                if (types[i].Name == typeName)
                    return types[i];
            }
        }

        return null;
    }

    private static string FindLatestBuildVersionDirectory(string buildOutputRoot, string packageName, BuildTarget buildTarget)
    {
        if (!Directory.Exists(buildOutputRoot))
            return null;

        string[] versionFiles = Directory.GetFiles(buildOutputRoot, $"{packageName}.version", SearchOption.AllDirectories);
        if (versionFiles == null || versionFiles.Length == 0)
            return null;

        string targetMark = "/" + buildTarget + "/";
        string[] targetMatched = versionFiles
            .Select(x => x.Replace("\\", "/"))
            .Where(x => x.IndexOf(targetMark, StringComparison.OrdinalIgnoreCase) >= 0)
            .ToArray();

        string[] finalFiles = targetMatched.Length > 0
            ? targetMatched
            : versionFiles.Select(x => x.Replace("\\", "/")).ToArray();

        string latestDir = finalFiles
            .Select(Path.GetDirectoryName)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderByDescending(x => Directory.GetLastWriteTimeUtc(x))
            .FirstOrDefault();

        return latestDir;
    }

    private static Dictionary<string, string> SnapshotBundleFileHashes(string versionDir, string packageName)
    {
        Dictionary<string, string> result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        if (string.IsNullOrEmpty(versionDir) || !Directory.Exists(versionDir))
            return result;

        string[] files = Directory.GetFiles(versionDir, "*", SearchOption.AllDirectories);
        foreach (string file in files)
        {
            if (ShouldIgnoreDiffFile(file, packageName))
                continue;

            string relative = Path.GetRelativePath(versionDir, file).Replace("\\", "/");
            result[relative] = CalcMD5(file);
        }

        return result;
    }

    private static bool ShouldIgnoreDiffFile(string filePath, string packageName)
    {
        string fileName = Path.GetFileName(filePath);
        string ext = Path.GetExtension(fileName).ToLowerInvariant();

        if (fileName.Equals($"{packageName}.version", StringComparison.OrdinalIgnoreCase))
            return true;

        switch (ext)
        {
            case ".hash":
            case ".json":
            case ".bytes":
            case ".report":
            case ".manifest":
            case ".meta":
            case ".txt":
            case ".log":
                return true;
        }

        return false;
    }

    private static string CalcMD5(string filePath)
    {
        using (var stream = File.OpenRead(filePath))
        using (var md5 = MD5.Create())
        {
            byte[] hash = md5.ComputeHash(stream);
            StringBuilder sb = new StringBuilder(hash.Length * 2);
            for (int i = 0; i < hash.Length; i++)
                sb.Append(hash[i].ToString("x2"));
            return sb.ToString();
        }
    }

    private string WriteBuildFailLog(string oldBuildDir, BuildResult buildResult)
    {
        string logDir = GetLogDirectory();
        string logPath = Path.Combine(logDir, $"{_packageName}_{_buildVersion}_{DateTime.Now:yyyyMMdd_HHmmss}_FAILED.txt");

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("========== YooAsset Build Log ==========");
        sb.AppendLine($"Time                     : {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"Package                  : {_packageName}");
        sb.AppendLine($"BuildVersion             : {_buildVersion}");
        sb.AppendLine($"BuildTarget              : {FixedBuildTarget}");
        sb.AppendLine($"BuildPipeline            : {EBuildPipeline.ScriptableBuildPipeline}");
        sb.AppendLine($"BuildOutputRoot          : {FixedBuildOutputRoot}");
        sb.AppendLine($"PreviousBuild            : {oldBuildDir}");
        sb.AppendLine($"ClearBuildCache          : {FixedClearBuildCache}");
        sb.AppendLine($"UseAssetDependDB         : {FixedUseAssetDependDB}");
        sb.AppendLine($"Compression              : {FixedCompressOption}");
        sb.AppendLine($"FileNameStyle            : {FixedFileNameStyle}");
        sb.AppendLine($"CopyBuildinFileOption    : {FixedCopyBuildinFileOption}");
        sb.AppendLine($"CopyBuildinFileParams    : {FixedCopyBuildinFileParams}");
        sb.AppendLine($"EncryptionServices       : {FixedEncryptionClassName}");
        sb.AppendLine($"ManifestProcessServices  : {FixedManifestProcessClassName}");
        sb.AppendLine($"ManifestRestoreServices  : {FixedManifestRestoreClassName}");
        sb.AppendLine($"Result                   : FAILED");
        sb.AppendLine($"FailedTask               : {buildResult.FailedTask}");
        sb.AppendLine($"ErrorInfo                : {buildResult.ErrorInfo}");
        sb.AppendLine($"ErrorStack               : {buildResult.ErrorStack}");

        File.WriteAllText(logPath, sb.ToString(), Encoding.UTF8);
        return logPath;
    }

    private string WriteBuildSuccessLog(
        string oldBuildDir,
        Dictionary<string, string> oldHashes,
        string newBuildDir,
        Dictionary<string, string> newHashes,
        UpAssetCopyResult upAssetResult)
    {
        string logDir = GetLogDirectory();
        string logPath = Path.Combine(logDir, $"{_packageName}_{_buildVersion}_{DateTime.Now:yyyyMMdd_HHmmss}.txt");

        HashSet<string> allKeys = new HashSet<string>(oldHashes.Keys, StringComparer.OrdinalIgnoreCase);
        allKeys.UnionWith(newHashes.Keys);

        List<string> changed = new List<string>();
        List<string> added = new List<string>();
        List<string> removed = new List<string>();

        foreach (string key in allKeys.OrderBy(x => x, StringComparer.OrdinalIgnoreCase))
        {
            bool hasOld = oldHashes.TryGetValue(key, out string oldHash);
            bool hasNew = newHashes.TryGetValue(key, out string newHash);

            string displayName = GetDisplayBundleName(key);

            if (hasOld && hasNew)
            {
                if (!string.Equals(oldHash, newHash, StringComparison.OrdinalIgnoreCase))
                    changed.Add($"[{displayName}]  {oldHash}  --------->  {newHash};");
            }
            else if (!hasOld && hasNew)
            {
                added.Add($"[{displayName}]  <new>  --------->  {newHash};");
            }
            else if (hasOld && !hasNew)
            {
                removed.Add($"[{displayName}]  {oldHash}  --------->  <removed>;");
            }
        }

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("========== YooAsset Build Log ==========");
        sb.AppendLine($"Time                     : {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"Package                  : {_packageName}");
        sb.AppendLine($"BuildVersion             : {_buildVersion}");
        sb.AppendLine($"BuildTarget              : {FixedBuildTarget}");
        sb.AppendLine($"BuildPipeline            : {EBuildPipeline.ScriptableBuildPipeline}");
        sb.AppendLine($"BuildOutputRoot          : {FixedBuildOutputRoot}");
        sb.AppendLine($"PreviousBuild            : {oldBuildDir}");
        sb.AppendLine($"CurrentBuild             : {newBuildDir}");
        sb.AppendLine($"UpAssetDirectory         : {upAssetResult.OutputDir}");
        sb.AppendLine($"ClearBuildCache          : {FixedClearBuildCache}");
        sb.AppendLine($"UseAssetDependDB         : {FixedUseAssetDependDB}");
        sb.AppendLine($"Compression              : {FixedCompressOption}");
        sb.AppendLine($"FileNameStyle            : {FixedFileNameStyle}");
        sb.AppendLine($"CopyBuildinFileOption    : {FixedCopyBuildinFileOption}");
        sb.AppendLine($"CopyBuildinFileParams    : {FixedCopyBuildinFileParams}");
        sb.AppendLine($"EncryptionServices       : {FixedEncryptionClassName}");
        sb.AppendLine($"ManifestProcessServices  : {FixedManifestProcessClassName}");
        sb.AppendLine($"ManifestRestoreServices  : {FixedManifestRestoreClassName}");
        sb.AppendLine($"Result                   : SUCCESS");
        sb.AppendLine();

        sb.AppendLine("---------- Summary ----------");
        sb.AppendLine($"Changed Bundles          : {changed.Count}");
        sb.AppendLine($"Added Bundles            : {added.Count}");
        sb.AppendLine($"Removed Bundles          : {removed.Count}");
        sb.AppendLine($"Copied To upAsset        : {upAssetResult.BundleFiles.Count}");
        sb.AppendLine($"Copied Meta To upAsset   : {upAssetResult.MetadataFiles.Count}");
        sb.AppendLine();

        sb.AppendLine("---------- Changed ----------");
        if (changed.Count == 0) sb.AppendLine("(none)");
        foreach (string line in changed) sb.AppendLine(line);
        sb.AppendLine();

        sb.AppendLine("---------- Added ----------");
        if (added.Count == 0) sb.AppendLine("(none)");
        foreach (string line in added) sb.AppendLine(line);
        sb.AppendLine();

        sb.AppendLine("---------- Removed ----------");
        if (removed.Count == 0) sb.AppendLine("(none)");
        foreach (string line in removed) sb.AppendLine(line);
        sb.AppendLine();

        sb.AppendLine("---------- upAsset Bundles ----------");
        if (upAssetResult.BundleFiles.Count == 0) sb.AppendLine("(none)");
        foreach (string line in upAssetResult.BundleFiles.OrderBy(x => x, StringComparer.OrdinalIgnoreCase))
            sb.AppendLine(line);
        sb.AppendLine();

        sb.AppendLine("---------- upAsset Metadata ----------");
        if (upAssetResult.MetadataFiles.Count == 0) sb.AppendLine("(none)");
        foreach (string line in upAssetResult.MetadataFiles.OrderBy(x => x, StringComparer.OrdinalIgnoreCase))
            sb.AppendLine(line);

        File.WriteAllText(logPath, sb.ToString(), Encoding.UTF8);
        return logPath;
    }

    private UpAssetCopyResult RefreshUpAssetDirectory(
        string newBuildDir,
        Dictionary<string, string> oldHashes,
        Dictionary<string, string> newHashes)
    {
        UpAssetCopyResult result = new UpAssetCopyResult
        {
            OutputDir = GetUpAssetOutputDirectory(newBuildDir)
        };

        ResetDirectory(result.OutputDir);

        HashSet<string> copiedFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        // 1. 复制变化 / 新增的 bundle
        foreach (var pair in newHashes.OrderBy(x => x.Key, StringComparer.OrdinalIgnoreCase))
        {
            string relativePath = pair.Key;
            bool hasOld = oldHashes.TryGetValue(relativePath, out string oldHash);
            bool isChangedOrAdded = !hasOld || !string.Equals(oldHash, pair.Value, StringComparison.OrdinalIgnoreCase);

            if (!isChangedOrAdded)
                continue;

            CopyRelativeFile(newBuildDir, relativePath, result.OutputDir);
            result.BundleFiles.Add(relativePath);
            copiedFiles.Add(relativePath);
        }

        // 2. 始终复制版本/清单相关文件，保证传到 S3 后可直接用于热更
        string[] allFiles = Directory.GetFiles(newBuildDir, "*", SearchOption.AllDirectories);
        foreach (string file in allFiles.OrderBy(x => x, StringComparer.OrdinalIgnoreCase))
        {
            string relativePath = Path.GetRelativePath(newBuildDir, file).Replace("\\", "/");
            if (!ShouldAlwaysCopyToUpAsset(relativePath, _packageName))
                continue;

            if (copiedFiles.Contains(relativePath))
                continue;

            CopyRelativeFile(newBuildDir, relativePath, result.OutputDir);
            result.MetadataFiles.Add(relativePath);
            copiedFiles.Add(relativePath);
        }

        return result;
    }

    private static string GetUpAssetOutputDirectory(string buildDir)
    {
        if (string.IsNullOrEmpty(buildDir))
            return string.Empty;

        string packageDir = Path.GetDirectoryName(buildDir);
        return Path.Combine(packageDir, "upAsset").Replace("\\", "/");
    }

    private static void ResetDirectory(string dir)
    {
        if (string.IsNullOrEmpty(dir))
            return;

        if (Directory.Exists(dir))
            Directory.Delete(dir, true);

        Directory.CreateDirectory(dir);
    }

    private static void CopyRelativeFile(string sourceRoot, string relativePath, string targetRoot)
    {
        string sourcePath = Path.Combine(sourceRoot, relativePath);
        string targetPath = Path.Combine(targetRoot, relativePath);

        string targetDir = Path.GetDirectoryName(targetPath);
        if (!string.IsNullOrEmpty(targetDir))
            Directory.CreateDirectory(targetDir);

        File.Copy(sourcePath, targetPath, true);
    }

    private static bool ShouldAlwaysCopyToUpAsset(string relativePath, string packageName)
    {
        if (string.IsNullOrEmpty(relativePath))
            return false;

        string fileName = Path.GetFileName(relativePath);
        string ext = Path.GetExtension(fileName).ToLowerInvariant();

        if (fileName.Equals($"{packageName}.version", StringComparison.OrdinalIgnoreCase))
            return true;

        switch (ext)
        {
            case ".hash":
            case ".json":
            case ".bytes":
            case ".manifest":
                return true;
            default:
                return false;
        }
    }

    private static string GetDisplayBundleName(string relativePath)
    {
        if (string.IsNullOrEmpty(relativePath))
            return string.Empty;

        string fileName = Path.GetFileName(relativePath);
        string ext = Path.GetExtension(fileName);
        if (!string.IsNullOrEmpty(ext))
            return Path.GetFileNameWithoutExtension(fileName);

        return fileName;
    }

    private static void OpenWithDefaultApp(string path)
    {
        if (string.IsNullOrEmpty(path) || !File.Exists(path))
            return;

        try
        {
            Process.Start(new ProcessStartInfo
            {
                FileName = path,
                UseShellExecute = true
            });
        }
        catch (Exception e)
        {
            Debug.LogWarning($"[CheckBundle] Open log failed : {e.Message}\nPath={path}");
            EditorUtility.RevealInFinder(path);
        }
    }

    private static string GetLogDirectory()
    {
        string projectRoot = Directory.GetParent(Application.dataPath).FullName;
        string logDir = Path.Combine(projectRoot, "Library", "CheckBundleLogs");
        Directory.CreateDirectory(logDir);
        return logDir;
    }

    private class GroupFolderInfo
    {
        public string AssetFolderPath;
        public string GroupName;
        public string AssetTag;
    }

    private class UpAssetCopyResult
    {
        public string OutputDir;
        public List<string> BundleFiles = new List<string>();
        public List<string> MetadataFiles = new List<string>();
    }
}